version: '3'

services:

  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile    
    image: mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  nginx:
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    restart: always
  
  wordpress:
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile    
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

networks:
  
  inception:
    driver: bridge

volumes:
  
  wordpress:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tictac/data/wordpress
  
  mariadb:
    name: mariadb_volumes
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tictac/data/mariadb
